const labels = {
  fa: {
    home: "خانه",
    products: "محصولات",
    available: "آماده مشاوره و سفارش",
    sku: "کد محصول",
    color: "انتخاب رنگ",
    allColors: "نمایش همه رنگ ها",
    price: "قیمت محصول",
    consultation: "درخواست مشاوره",
    preciseInformation: "مشخصات این محصول با دقت ثبت شده است",
    directSupport: "برای انتخاب بهتر، کارشناسان ما همراه شما هستند",
    description: "توضیحات محصول",
    specifications: "مشخصات فنی",
    related: "محصولات مرتبط",
    noDescription: "توضیحات این محصول هنوز تکمیل نشده است.",
    yes: "بله",
    no: "خیر",
    unknown: "—",
  },
  ar: {
    home: "الرئيسية",
    products: "المنتجات",
    available: "متاح للاستشارة والطلب",
    sku: "رمز المنتج",
    color: "اختر اللون",
    allColors: "عرض جميع الألوان",
    price: "سعر المنتج",
    consultation: "طلب استشارة",
    preciseInformation: "تم تسجيل مواصفات هذا المنتج بعناية",
    directSupport: "فريقنا يساعدك في اختيار المنتج المناسب",
    description: "وصف المنتج",
    specifications: "المواصفات الفنية",
    related: "منتجات ذات صلة",
    noDescription: "لم يتم استكمال وصف هذا المنتج بعد.",
    yes: "نعم",
    no: "لا",
    unknown: "—",
  },
  en: {
    home: "Home",
    products: "Products",
    available: "Available for consultation and order",
    sku: "Product code",
    color: "Choose a color",
    allColors: "Show all colors",
    price: "Product price",
    consultation: "Request consultation",
    preciseInformation: "This product's specifications are carefully recorded",
    directSupport: "Our team can help you choose the right product",
    description: "Product description",
    specifications: "Technical specifications",
    related: "Related products",
    noDescription: "This product description has not been completed yet.",
    yes: "Yes",
    no: "No",
    unknown: "—",
  },
} as const;

export function productDetailCopy(locale: string) {
  return labels[locale as keyof typeof labels] ?? labels.en;
}
