DELETE FROM `home_sections` WHERE `type` = 'STORIES';

ALTER TABLE `home_sections`
  MODIFY `type` ENUM('HERO', 'CATEGORIES', 'FEATURED_PRODUCT', 'SELECTED_PRODUCTS', 'BENEFITS', 'BLOG', 'CONTACT', 'BANNER_FULL', 'BANNER_SPLIT') NOT NULL;
