const catalogLabels = {
  fa: {
    eyebrow: "LIFE STEEL COLLECTION",
    title: "محصولات استیل",
    description: "مجموعه حوله خشک کن ها و رادیاتورهای استیل لایف استیل",
    filters: "فیلتر محصولات",
    search: "جستجوی محصول",
    categories: "دسته بندی",
    allCategories: "همه دسته بندی ها",
    attributes: "ویژگی محصول",
    allAttributes: "همه ویژگی ها",
    allOptions: "همه گزینه ها",
    min: "حداقل مقدار",
    max: "حداکثر مقدار",
    all: "همه",
    yes: "بله",
    no: "خیر",
    hasValue: "دارای مقدار",
    price: "محدوده قیمت",
    minPrice: "حداقل قیمت",
    maxPrice: "حداکثر قیمت",
    apply: "اعمال فیلترها",
    clear: "پاک کردن فیلترها",
    close: "بستن فیلترها",
    results: "محصول",
    sort: "مرتب سازی",
    defaultSort: "پیش فرض",
    newest: "جدیدترین",
    oldest: "قدیمی ترین",
    empty: "محصولی با این شرایط پیدا نشد.",
    pages: "صفحه بندی محصولات",
  },
  ar: {
    eyebrow: "LIFE STEEL COLLECTION",
    title: "منتجات الستانلس ستيل",
    description: "مجموعة مجففات المناشف ومشعات الستانلس ستيل من لايف ستيل",
    filters: "تصفية المنتجات",
    search: "ابحث عن منتج",
    categories: "التصنيف",
    allCategories: "جميع التصنيفات",
    attributes: "ميزة المنتج",
    allAttributes: "جميع الميزات",
    allOptions: "جميع الخيارات",
    min: "الحد الأدنى",
    max: "الحد الأقصى",
    all: "الكل",
    yes: "نعم",
    no: "لا",
    hasValue: "له قيمة",
    price: "نطاق السعر",
    minPrice: "أقل سعر",
    maxPrice: "أعلى سعر",
    apply: "تطبيق الفلاتر",
    clear: "مسح الفلاتر",
    close: "إغلاق الفلاتر",
    results: "منتج",
    sort: "الترتيب",
    defaultSort: "الافتراضي",
    newest: "الأحدث",
    oldest: "الأقدم",
    empty: "لم يتم العثور على منتجات مطابقة.",
    pages: "صفحات المنتجات",
  },
  en: {
    eyebrow: "LIFE STEEL COLLECTION",
    title: "Stainless steel products",
    description: "Life Steel towel warmers and stainless steel radiators",
    filters: "Product filters",
    search: "Search products",
    categories: "Category",
    allCategories: "All categories",
    attributes: "Product attribute",
    allAttributes: "All attributes",
    allOptions: "All options",
    min: "Minimum value",
    max: "Maximum value",
    all: "All",
    yes: "Yes",
    no: "No",
    hasValue: "Has a value",
    price: "Price range",
    minPrice: "Minimum price",
    maxPrice: "Maximum price",
    apply: "Apply filters",
    clear: "Clear filters",
    close: "Close filters",
    results: "products",
    sort: "Sort by",
    defaultSort: "Default",
    newest: "Newest",
    oldest: "Oldest",
    empty: "No matching products found.",
    pages: "Product pages",
  },
} as const;

export function productCatalogCopy(locale: string) {
  return catalogLabels[locale as keyof typeof catalogLabels] ?? catalogLabels.en;
}
